package org.jbpm.ios_rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Io implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "IO ID")
   private java.math.BigInteger io_id;

   @org.kie.api.definition.type.Label(value = "Wins")
   private java.math.BigInteger wins;

   @org.kie.api.definition.type.Label(value = "Clicks")
   private java.math.BigInteger clicks;

   @org.kie.api.definition.type.Label(value = "Impressions")
   private java.math.BigInteger impressions;

   @org.kie.api.definition.type.Label(value = "Creative")
   private java.math.BigInteger creative_id;

   @org.kie.api.definition.type.Label(value = "Start Time")
   private java.util.Date start_time;

   @org.kie.api.definition.type.Label(value = "Conversions")
   private java.math.BigInteger conversions;

   @org.kie.api.definition.type.Label(value = "End Time")
   private java.util.Date end_time;

   @org.kie.api.definition.type.Label(value = "Status")
   private java.lang.String status;

   public Io()
   {
   }

   public java.math.BigInteger getIo_id()
   {
      return this.io_id;
   }

   public void setIo_id(java.math.BigInteger io_id)
   {
      this.io_id = io_id;
   }

   public java.math.BigInteger getWins()
   {
      return this.wins;
   }

   public void setWins(java.math.BigInteger wins)
   {
      this.wins = wins;
   }

   public java.math.BigInteger getClicks()
   {
      return this.clicks;
   }

   public void setClicks(java.math.BigInteger clicks)
   {
      this.clicks = clicks;
   }

   public java.math.BigInteger getImpressions()
   {
      return this.impressions;
   }

   public void setImpressions(java.math.BigInteger impressions)
   {
      this.impressions = impressions;
   }

   public java.math.BigInteger getCreative_id()
   {
      return this.creative_id;
   }

   public void setCreative_id(java.math.BigInteger creative_id)
   {
      this.creative_id = creative_id;
   }

   public java.util.Date getStart_time()
   {
      return this.start_time;
   }

   public void setStart_time(java.util.Date start_time)
   {
      this.start_time = start_time;
   }

   public java.math.BigInteger getConversions()
   {
      return this.conversions;
   }

   public void setConversions(java.math.BigInteger conversions)
   {
      this.conversions = conversions;
   }

   public java.util.Date getEnd_time()
   {
      return this.end_time;
   }

   public void setEnd_time(java.util.Date end_time)
   {
      this.end_time = end_time;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public Io(java.math.BigInteger io_id, java.math.BigInteger wins,
         java.math.BigInteger clicks, java.math.BigInteger impressions,
         java.math.BigInteger creative_id, java.util.Date start_time,
         java.math.BigInteger conversions, java.util.Date end_time,
         java.lang.String status)
   {
      this.io_id = io_id;
      this.wins = wins;
      this.clicks = clicks;
      this.impressions = impressions;
      this.creative_id = creative_id;
      this.start_time = start_time;
      this.conversions = conversions;
      this.end_time = end_time;
      this.status = status;
   }

}